### PR TITLE
Bugfix/plot spacing

### PR DESCRIPTION
**Pull request by SimonCW**
Hi @sangonzal , 

thanks for the action! I added some horizontal spacing between the two subplots to show the full date. 

I also noticed that the year is screwed up on the [plot axes](https://github.com/sangonzal/repository-traffic-action/blob/insights/traffic/plots.png). My first suspicion was that the mixture of `datetime.datetime` and `pd.TimeStamp` in the `updated_dict` is causing this, however, I couldn't reproduce this locally. If you have other suspicions let me know and I'll try to fix it. 

Best
Simon

### CODE REVIEW

**Comment by sangonzal** [comment]
@SimonCW Thanks! The date issue on the plot is weird, when I run it locally the date on the plots is correct. I don't know why it's not formatted correctly when it's run on a VM. If you don't get to it first, I'll try to take a look in the upcoming days. 

Let me know if you want to merge this without the year fix, I'll do a release to the marketplace with your changes.

**Comment by SimonCW** [comment]
Hi @sangonzal, from my point of view we can wait with the release until we fix the time formatting issue.  

Then, you experience the same weird behavior as I am: locally it is working fine. Unfortunately, I have no experience with developing Github actions, so I don't know of how much help I can be. I'll download https://github.com/nektos/act and try to get the traffic action running for my repo locally in their containers to see whether I can reproduce the behavior there.

**Comment by sangonzal** [comment]
@SimonCW This seemed to be a bug with pandas - https://github.com/pandas-dev/pandas/issues/34850

I've updated the version of pandas and that seemed to the year issue. Going to merge your PR and draft a release. You should be able to reference the latest changes by using version 0.1.4

**Comment by sangonzal** [comment]
@SimonCW v0.1.4 released! thanks for bringing this to my attention and fixing the spacing issue.

**Pull request merged**
